spring.application.name=rotationmanagement

spring.datasource.url=jdbc:mariadb://localhost:3306/rotationmanagement_db
spring.datasource.username=competency_user
spring.datasource.password=competency_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.port=8080