api.base=/api

api.apprentice=${api.base}/apprentices
api.rotation=${api.base}/rotations
api.competency=${api.base}/competencies
api.assignment=${api.base}/assignments
api.matching=${api.base}/matching